# Generated by Django 3.2.11 on 2022-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=8)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=5)),
                ('product_name', models.CharField(max_length=50)),
                ('product_rate1', models.FloatField()),
                ('product_rate2', models.FloatField()),
                ('product_rate3', models.FloatField()),
            ],
        ),
    ]
