# Generated by Django 3.2.11 on 2022-01-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20220106_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='product_rate_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='product_rate_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='product_rate_3',
            field=models.FloatField(default=0),
        ),
    ]
